src/main/java/za/co/vzs/store/domain/Address.java
package za.co.vzs.store.domain;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.Size;

/**
 * Entity implementation class for Entity: Address
 * 
 */
@Entity
public class Address implements Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int id;
	@Size(min = 1, max = 64)
	private String firstLine;
	@Size(min = 1, max = 8)
	private String postalCode;

	private static final long serialVersionUID = 1L;

	public Address() {
		super();
	}

	public String getFirstLine() {
		return this.firstLine;
	}

	public void setFirstLine(String firstLine) {
		this.firstLine = firstLine;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

}

src/main/java/za/co/vzs/store/domain/Audit.java
package za.co.vzs.store.domain;

import java.io.Serializable;
import java.util.Calendar;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Entity implementation class for Entity: AuditRecord
 *
 */
@Entity
public class Audit implements Serializable {
	
	public enum UpdateType {
		CREATE, UPDATE, DELETE
	}
	
    private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	private int id;
	private Calendar date;	
	private int entityId;
	@Enumerated(EnumType.STRING)
	private UpdateType type;
			
	public Audit() {		
	}
		
	public Audit(UpdateType type) {		
		this.type = type;
	}

	public Calendar getDate() {
		return this.date;
	}

	public void setDate(Calendar date) {
		this.date = date;
	}   
     
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEntityId() {
		return entityId;
	}

	public void setEntityId(int customerId) {
		this.entityId = customerId;
	}

	public UpdateType getType() {
		return type;
	}

	public void setType(UpdateType type) {
		this.type = type;
	}		
	   
}

src/main/java/za/co/vzs/store/domain/Customer.java
package za.co.vzs.store.domain;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;

/**
 * Entity implementation class for Entity: Customer
 *
 */
@Entity

public class Customer implements Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	private int id;
	@Size(min=1, max=32)
	private String firstName;
	@Size(min=1, max=32)
	private String lastName;
    @OneToOne(cascade = CascadeType.ALL,orphanRemoval = true)
	private Address billingAddress;
    @Email
	private String email;
	
	private static final long serialVersionUID = 1L;

	public Customer() {
		super();
	}

	public int getId() {
		return id;
	}	

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String name) {
		this.firstName = name;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Address getBillingAddress() {
		return billingAddress;
	}

	public void setBillingAddress(Address billingAddress) {
		this.billingAddress = billingAddress;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email.toLowerCase();
	}

	@Override
	public String toString() {
		return "Customer [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + "]";
	}

}

src/main/java/za/co/vzs/store/web/CustomerBean.java
package za.co.vzs.store.web;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import org.apache.log4j.Logger;

import za.co.vzs.store.domain.Address;
import za.co.vzs.store.domain.Customer;
import za.co.vzs.store.service.CustomerService;
import za.co.vzs.store.service.ValidationException;

@Named("customerBean")
@RequestScoped
public class CustomerBean {

	final static Logger logger = Logger.getLogger(CustomerBean.class);

	public CustomerBean() {
	}

    @EJB	
	private CustomerService customerService;

	private String firstName;
	private String lastName;
	private String addressFirstLine;
	private String postalCode;
	private String email;

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String name) {
		this.firstName = name;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAddressFirstLine() {
		return this.addressFirstLine;
	}

	public void setAddressFirstLine(String firstLine) {
		this.addressFirstLine = firstLine;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String contact) {
		this.email = contact;
	}

	public String submit() {
		String nextPage = "";
		Customer customer = new Customer();
		customer.setFirstName(firstName);
		customer.setLastName(lastName);
		customer.setEmail(email);
		Address billingAddress = new Address();
		billingAddress.setFirstLine(addressFirstLine);
		billingAddress.setPostalCode(postalCode);
		customer.setBillingAddress(billingAddress);
		try {
			customerService.addCustomer(customer);
			nextPage = "add-success?faces-redirect=true&amp;includeViewParams=true";
		} catch (ValidationException e) {
			addMessage(getMessage(e.getErrorCode()));
		} catch (EJBException ex) {
			logger.error("Failed to add customer.", ex);			
			addMessage(ResourceBundle.getBundle("customerbundle").getString("CustomerSubmitFailed"));
		}
		return nextPage;
	}

	private void addMessage(String message) {
		FacesContext context = FacesContext.getCurrentInstance();
		context.addMessage(null, new FacesMessage(message));
	}

	private String getMessage(String errorCode) {
		String errorMessage;
		try {
			errorMessage = ResourceBundle.getBundle("errormap").getString(errorCode);
		} catch (MissingResourceException ex) {
			errorMessage = "Unknown error.";
		}
		return errorMessage;
	}

}

src/main/java/za/co/vzs/store/web/DebugBean.java
package za.co.vzs.store.web;

import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import za.co.vzs.store.domain.Audit;
import za.co.vzs.store.domain.Customer;
import za.co.vzs.store.persistence.AuditResource;
import za.co.vzs.store.service.CustomerService;

@Named("debugBean")
@RequestScoped
public class DebugBean {

	@EJB
	private CustomerService customerService;
	@Inject
	private AuditResource auditResource;

	public DebugBean() {
	}

	public List<Customer> getCustomers() {
		return customerService.getCustomers();
	}
	
	public List<Audit> getAuditRecords(){
		return auditResource.findAll();
	}

}

src/main/webapp/add-success.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<f:loadBundle basename="customerbundle" var="bundle" />

<h:head>
	<title><ui:insert name="add-success">#{bundle.SuccessHeading}</ui:insert></title>

</h:head>
<h:body>
	<div>#{bundle.CustomerUpdateSuccess}</div>	
	<br/>	
	<h:link value="#{bundle.AddCustomerLink}" outcome="addcustomer" />
	<br/>
	<h:link value="#{bundle.DebugViewLink}" outcome="debug" />
	<br/>
</h:body>
</html>

src/main/webapp/addcustomer.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<h:outputStylesheet library="css" name="style.css" />
<f:loadBundle basename="customerbundle" var="bundle" />

<h:head>
	<title>#{bundle.AddCustomerHeading}</title>
</h:head>
<body>
	<h:form>
		<h:panelGrid class="cust-table" columns="3">
			<h:outputLabel for="firstName">#{bundle.FirstName}</h:outputLabel>
			<h:inputText id="firstName" value="#{customerBean.firstName}"
				maxlength="32" required="true"
				requiredMessage="#{bundle.FirstNameRequired}">
			</h:inputText>
			<br />
			<h:outputLabel for="lastName">#{bundle.LastName}</h:outputLabel>
			<h:inputText id="lastName" value="#{customerBean.lastName}"
				maxlength="32" required="true"
				requiredMessage="#{bundle.LastNameRequired}">
			</h:inputText>
			<br />
			<h:outputLabel for="addressFirstLine">#{bundle.Address}</h:outputLabel>
			<h:inputText id="addressFirstLine"
				value="#{customerBean.addressFirstLine}" maxlength="64"
				required="true" requiredMessage="#{bundle.AddressRequired}">
			</h:inputText>
			<br />
			<h:outputLabel for="postalCode">#{bundle.PostalCode}</h:outputLabel>
			<h:inputText id="postalCode" value="#{customerBean.postalCode}"
				maxlength="8" required="true"
				requiredMessage="#{bundle.PostalCodeRequired}">
			</h:inputText>
			<br />
			<h:outputLabel for="email">#{bundle.Email}</h:outputLabel>
			<h:inputText id="email" value="#{customerBean.email}" required="true"
				label="Email" validatorMessage="#{bundle.InvalidEmailMessage}"
				requiredMessage="#{bundle.EmailRequiredMessage}">
				<f:validateRegex pattern="([^.@]+)(\.[^.@]+)*@([^.@]+\.)+([^.@]+)" />
			</h:inputText>
		</h:panelGrid>
		<h:commandButton action="${customerBean.submit()}" id="submit-button"
			value="#{bundle.Submit}">
		</h:commandButton>
		<h:messages style="color:red">
		</h:messages>
	</h:form>
</body>
</html>

src/main/webapp/debug.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<f:loadBundle basename="customerbundle" var="bundle" />
<h:head>
	<title>#{bundle.ListCustomerHeading}</title>
</h:head>
<body>
	<div>
	<h3> Customers table:</h3>
		<h:dataTable value="#{debugBean.customers}" var="customer" border="1">
			<h:column>
				<f:facet name="header">Id</f:facet>			
    				#{customer.id}
    			</h:column>
			<h:column>
				<f:facet name="header">#{bundle.FirstName}</f:facet>
    				#{customer.firstName}
    			</h:column>
			<h:column>
				<f:facet name="header">#{bundle.LastName}</f:facet>
    				#{customer.lastName}
    			</h:column>
			<h:column>
				<f:facet name="header">#{bundle.Address}</f:facet>
    				#{customer.billingAddress.firstLine}
    			</h:column>
			<h:column>
				<f:facet name="header">#{bundle.PostalCode}</f:facet>
    				#{customer.billingAddress.postalCode}
    			</h:column>
			<h:column>
				<f:facet name="header">#{bundle.Email}</f:facet>
    				#{customer.email}
    			</h:column>
		</h:dataTable>
	</div>
	<div>
	<h3>Audit table:</h3>
		<h:dataTable value="#{debugBean.auditRecords}" var="auditRecord"
			border="1">
			<h:column>
				<f:facet name="header">ID</f:facet>
    				#{auditRecord.id}
    			</h:column>
			<h:column>
				<f:facet name="header">Date</f:facet>			
    				#{auditRecord.date.time}
    			</h:column>
			<h:column>
				<f:facet name="header">Entity ID</f:facet>
    				#{auditRecord.entityId}
    			</h:column>
			<h:column>
				<f:facet name="header">Update Type</f:facet>
    				#{auditRecord.type.toString()}
    			</h:column>
		</h:dataTable>
	</div>
</body>
</html>

src/main/webapp/general-error.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<f:loadBundle basename="customerbundle" var="bundle" />
<h:head>
	<title>#{bundle.ErrorPageHeading}</title>
</h:head>
<body>
	<div>#{bundle.UnknownErrorMessage}</div>
</body>
</html>